[package]
name = "test_logger"
version = "0.1.0"
authors = ["Beni <benireydman901@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
log4rs = "0.13.0"